version: "3.9"
services:
  service-postgres15:
    image: postgres:15-alpine
    restart: always
    ports:
      - "${PORT_EXPOSE_POSTGRES}:5432"
    volumes:
      - ${VOL_PG}:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: hashticket
      POSTGRES_DB: tickets
      POSTGRES_PASSWORD: 12345678
      PGDATA: /var/lib/postgresql/data/pgdata
  server-discovery:
    image: localhost:${PORT_REGISTRY}/server-discovery:latest
    ports:
     - "1111:1111"
    environment:
     - PROFILE_JAR=prod
  service-gateway:
    image: localhost:${PORT_REGISTRY}/server-gateway:latest
    ports:
     - "5004:5004"
    environment:
     - PROFILE_JAR=prod
     - SERVER_DISCOVERY=server-discovery
    depends_on:
     - service-postgres15
     - server-discovery
  service-acceso-datos:
    image: localhost:${PORT_REGISTRY}/server-acceso-datos:latest
    environment:
     - PROFILE_JAR=prod
     - SERVER_DISCOVERY=server-discovery
     - SERVER_BD=service-postgres15
    depends_on:
     - service-postgres15
     - server-discovery
    volumes:
     - /volumenes/vol_logs:/opt/logs
  service-business:
    image: localhost:${PORT_REGISTRY}/server-business:latest
    environment:
     - PROFILE_JAR=prod
     - SERVER_DISCOVERY=server-discovery
     - SERVER_DATOS=service-acceso-datos
    depends_on:
     - service-postgres15
     - server-discovery
    volumes:
     - ${VOL_REPO}:/opt/repository
     - /volumenes/vol_logs:/opt/logs
  service-public-user:
    image: localhost:${PORT_REGISTRY}/server-public-user:latest
    environment:
     - PROFILE_JAR=prod
     - SERVER_DISCOVERY=server-discovery
     - SERVER_BD=service-postgres15
    depends_on:
     - service-postgres15
     - server-discovery
    volumes:
     - ${VOL_REPO}:/opt/repository
     - /volumenes/vol_logs:/opt/logs
